feature: agregar JWT como inicio de sesión
d-salazar-se/fdi-usa20107-api pull request #3
Opened 2022-04-29 22:57 UTC by BHernandez18

Cualquier conflicto con la base de datos, ejecutar lo siguiente:

1. `rails db:drop`
2. `rails db:create`
3. `rails db:migrate`
4. `rails db:seed`

2022-05-09 03:49 UTC, d-salazar commented on app/controllers/auth_controller.rb
> +        @user.update_from_login(@payload)
Falta renderizar un 401 en caso de que el usuario no exista.

```ruby
if ! @user
  render(...401...)
  return false
end
```

2022-05-09 04:14 UTC, d-salazar requested changes

2022-05-09 04:14 UTC, d-salazar commented on config/routes.rb
> +  resources :auth, except: [:index, :create, :show, :update, :destroy] do
No le veo mucho sentido a usar `resources` si todos los métodos de resource estan en `except`

2022-05-09 04:14 UTC, d-salazar commented on app/controllers/auth_controller.rb
> +  end
Si no estamos haciendo nada con el, removamos el `logout`

2022-05-09 04:14 UTC, d-salazar commented on config/routes.rb
> +      get :logout
Mismo de arriba

2022-05-10 06:56 UTC, BHernandez18 commented on app/controllers/auth_controller.rb
> +        @user.update_from_login(@payload)
Encapsule esa lógica en el modelo y cambié el método empleado para que lance un error si es que no llega a encontrarse el usuario.

```ruby
# Método inicial --> Retorna 'nil' si es que no encuentra al usuario
User.find_by(...)

# Nuevo método --> Retorna 'ActiveRecord::RecordNotFound' si es que no encuentra al usuario
User.find_by!(...)
```

2022-05-10 07:02 UTC, BHernandez18 commented on config/routes.rb
> +  resources :auth, except: [:index, :create, :show, :update, :destroy] do
Aunque es cierto que es innecesario, resulta más cómodo después añadir otras posibles rutas dentro de dicho `namespace` y evitamos una declaración "hardcodeada" de la ruta. Así mismo, las rutas autogeneradas por el uso de `resources ...` hay que quitarlas porque no están definidas en el controlador.

2022-05-10 07:04 UTC, BHernandez18 commented on app/controllers/auth_controller.rb
> +  end
De momento creo que no habría mayor preocupación por no tener `logout`. Cualquier cosa, después se puede discutir mejor cual será el mecanismo para efectuarlo.

2022-05-10 07:06 UTC, BHernandez18 commented on config/routes.rb
> +      get :logout
Nada que temer, se ve más bonito así como está.

2022-05-12 03:29 UTC, d-salazar-se approved these changes

2022-05-12 03:29 UTC, d-salazar approved these changes

2022-05-12 03:36 UTC, merged